### ISSUE TITLE
Read port from ssh config file (e.g. /home/user/.ssh/config)

### ISSUE THREAD

**Issue by atomic111** [inspec/train#101]
### Description

Read port also from the ssh config under /home/user.ssh/config.
### InSpec and Platform Version

inspec version is 0.20.1 and archlinux 4.5.2-1-ARCH
### Replication Case

/home/user/.ssh/config look like this

Host jumphost
        Hostname 1.1.1.1
        Port 28646

inspec exec ./ -t ssh://root@jumphost --key-files /home/user/.ssh/id_rsa is not working because of the port. I have to add the Port also

inspec exec ./ -t ssh://root@jumphost --key-files /home/user/.ssh/id_rsa --port 28646

I think train read the config partly, because i can use the configured hostnames in /home/user/.ssh/config.

**Comment by chris-rock** [comment]
Great idea @atomic111

**Comment by marcparadise** [comment]
This also applies to username - if User is specified in .ssh/config, but no user is given in train options, user will be defaulted to 'root' instead of the .ssh/config value for the host. 
I'm taking a stab at correcting this, and will include User and Port.

**Comment by clintoncwolfe** [comment]
We may be over-defualating this - net-ssh will respect the config file.
