### ISSUE TITLE
reestablish support for ruby 1.9.3?

### ISSUE THREAD

**Issue by chris-rock** [inspec/train#124]
https://github.com/chef/train/pull/123 introduced the winrm 2 dependency that supports ruby 2.x only. We should decouple the transports dependencies from train, so that we are able to support older systems with ruby 1.9.3 as well, even if they are not able to use all features.

**Comment by clintoncwolfe** [comment]
At this point in Aug 2018, we support Ruby 2.3 - 2.5 only.
