### ISSUE TITLE
OSX and probably all BSDs fail with sudo-password

### ISSUE THREAD

**Issue by thomascate** [inspec/train#136]
Hi,

Currently the ssh transport uses `base64 -d` during auth for sudo with password. However on BSD machines the flag is -D.

`inspec exec -t ssh://tcate@10.1.1.71 -i key ~/.ssh/id_rsa --sudo --sudo-password 'hunter2'
Sudo failed:  base64: invalid option -- d
Usage:  base64 [-dhvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
Password:`

**Comment by clintoncwolfe** [comment]
Refs #445

**Comment by clintoncwolfe** [comment]
Appears fixed on #137
