### ISSUE TITLE
Unify --keys handling

### ISSUE THREAD

**Issue by arlimus** [inspec/train#15]
Several transports can use a key file - including SSH and WinRM.  I believe this issue proposes using one option to refer to both.

**Comment by srenatus** [comment]
Please provide more content. :smile:

**Comment by clintoncwolfe** [comment]
See https://github.com/inspec/inspec/issues/3681, which proposes keeping all transport options namespaced by a prefix based on transport name

**Comment by clintoncwolfe** [comment]
Based on 3681, I think we are going to go in the opposite direction.
