### ISSUE TITLE
Create http/https/tcp/udp transports

### ISSUE THREAD

**Issue by jquick** [inspec/train#238]
### Train-API

The Train-API subsystem supports non-OS platforms targets. It provides the `tcp`, `udp`, and `unix` transports for low-level socket access, as well as  `http` and `https` for high-level transport implementations.

These are defined via the URI schema:

```
mandatory minimum:
[tcp|upd|unix|http|https]://host

all options:
[tcp|upd|unix|http|https]://[user[:password]@]host[:port]][/path][?query][#fragment]
```

Some of these fields may not apply to certain transports. There may be resources that are based on the `tcp` transport but don't process a `path` or `query` parameter (e.g. for low-level interface testing).

The `tcp`, `udp`, and `unix` transports will all provide a low-level socket object with a basic communication interface (using an abstraction on top of the underlying [Socket](https://ruby-doc.org/stdlib-2.4.1/libdoc/socket/rdoc/Socket.html) object). It is exposed to all InSpec resources via `inspec.backend` including all configuration options.

The `http` and `https` transports offer a simpler interface for all RESTful endpoints, exposed as the `inspec.backend` object to InSpec resources. Apart from the simple `request` it is also possible to use HTTP verbs (`get`, `post`, `put`, `options`, `delete`, `head`, `trace`).

**Comment by adamleff** [comment]
I think this would be a really neat addition to Train, but I would hold off on any implementation work until we have a real need / use case that we can use to model how this might look. Otherwise, we're throwing stuff against a wall to see if it sticks.

**Comment by zenspider** [comment]
Closing until we have need.
