### ISSUE TITLE
Add support for Docker + TCP Sockets

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/train#240]
Currently, we only support Unix socket connections for targeting the Docker API. Unix sockets are not supported on Windows at this time so if we want to target containers on a Windows Docker host the user must reconfigure Docker to listen on a TCP socket.

Then we must make train make the correct call to the `docker` gem since it currently defaults to a Unix socket, https://github.com/swipely/docker-api/blob/master/lib/docker/connection.rb#L11

See issue https://github.com/chef/inspec/issues/2379 for more details

**Comment by lmayorga1980** [comment]
:+1:

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
