### ISSUE TITLE
train over AWS SSM?

### ISSUE THREAD

**Issue by brandoconnor** [inspec/train#304]
### Description

SSH connectivity to EC2 instances when done right are often established through a bastion host. Increasingly, bastion hosts are being displaced in favor of proxying commands through AWS Systems Manager (SSM), thereby removing a somewhat vulnerable and often forgotten piece of infrastructure. `train` "supports" execution via ssh through bastions today through a somewhat hacky way (basically configure `~/.ssh/config`; no supported flags). It would be excellent if train also supported using SSM for test execution/transport as direct or indirect SSH access becomes unnecessary. We just need the SSM agent present, connectivity to AWS, and a suitable IAM user/role/policy.

### Train and Platform Version

All.

### Possible Solutions

I haven't yet dug into the code here to figure out where and how this could be implemented. It's better to start a conversation around the idea first.

SSM isn't a direct drop in for SSH and comes with its own way of managing documents of potential executable commands. I'm mostly wondering if anyone familiar enough with both train and SSM has considered this alternative approach and if they met any significant roadblocks, including project direction.

**Comment by chris-rock** [comment]
@brandoconnor Thank you very much for that idea. We tried to prototype a backend that uses the ec2 run command as the backend. The challenge with that approach is that it is difficult (not impossible) to implement and even more difficult to maintain. You would need to track multiple ec2 run command calls and the output files for those commands are difficult to parse.

I think you will like what we are going to announce at ChefConf. Therefore, I'd like to revisit your question next week.
