### ISSUE TITLE
Need push transport

### ISSUE THREAD

**Issue by lamont-granquist** [inspec/train#31]
The code in knife-push can be most likely pretty easily adapted to this, although it'll bring in the chef gem and Chef::REST as run-time deps to the project (and if some upstream consumer of this gem also depends on chef, or if chef at some point pulls in this gem, then you wind up with diamond or circular deps).

**Comment by chris-rock** [comment]
@lamont-granquist Great idea to add more transports. In general we try to keep the dependencies in train reduced in order to ensure it is fast and lightweight. This project focuses on transport only. Can we find an abstraction e.g. Rest Commands for Chef Push and leave other parts within a knife implementation?

**Comment by lamont-granquist** [comment]
Well the knife-push code could be copypasta'd, its not much, so you don't have to bring in knife-push as a dependency.  The problem is that you'd want to leverage Chef::REST or Chef::ServerAPI and right now those aren't available as libraries so that would slurp in the entire chef-client as a runtime dep.

**Comment by chris-rock** [comment]
The idea of `train` is to be a lightweight framework for command execution and file transfer to the machine. I believe that we should not include the chef gem here. May it make sense to extract the required modules and turn this into a small gem with no dependencies?

**Comment by lamont-granquist** [comment]
I would love to see Chef::HTTP/Chef::REST/Chef::ServerAPI extracted out to a library for exactly this kind of purpose.

**Comment by clintoncwolfe** [comment]
As there has not been much motion on this in the last 3 years, I'm going to close this - if there is demand for this, please feel free to re-open.
