### ISSUE TITLE
Alpine Support

### ISSUE THREAD

**Issue by damacus** [inspec/train#322]
### Description

Alpine should be detected so we can test the popular docker platform.

### Train and Platform Version

(from ChefDK): `1.4.4`

### Replication Case

Add support to inspec for the Alpine package provider, there is no `alpine` platform.

### Possible Solutions

- Not sure yet.

**Comment by chris-rock** [comment]
@damacus alpine is properly supported in InSpec and train https://github.com/inspec/train/blob/master/lib/train/platforms/detect/specifications/os.rb#L285-L291:

```
$ inspec detect -t docker://09a05fc4688c                                                                                                      

== Platform Details

Name:      alpine
Families:  linux, unix, os
Release:   3.7.0
Arch:      x86_64
```

Can you elaborate where you see incompatibilities?

**Comment by chris-rock** [comment]
I close this, since @damacus already identified the missing piece via https://github.com/inspec/inspec/pull/3215
