### ISSUE TITLE
Plan on using aws-sdk 3

### ISSUE THREAD

**Issue by frezbo** [inspec/train#350]
Any plans on using aws-sdk 3?

**Comment by clintoncwolfe** [comment]
Tracking on https://github.com/inspec/inspec/issues/2571 . Generally speaking, we're technically ready, but need to coordinate.

**Comment by frezbo** [comment]
This is forcing me to monkey patch aws-sdk with v3 features. Hope this gets fixed soon. :+1:

**Comment by clintoncwolfe** [comment]
Train 2.0, released today, has its depedency on `aws-sdk v2` removed; also removed is the AWS transport.  

The Train plugin `train-aws`, pushed to rubygems today, contains the transport and a dependency on `aws-sdk-core` v3 and a handful of service gems.
