### ISSUE TITLE
Train leftover PowerShell process on local transport

### ISSUE THREAD

**Issue by jquick** [inspec/train#358]
Train leftover PowerShell process

Issue Summary: Orphaned PowerShell processes are stacking up after being spawned by Inspec/train for audit runs on Windows Server 2012 R2

Expected Results: powershell.exe killed appropriately

Actual Results: powershell.exe processes hanging around

Repro Steps (if possible): I have not been able to reproduce

Request for Developers: Debug assistance

Customer scanning with Audit Cookbook and compliance profile "DevSec Windows Security Baseline". When he decodes the parameter for the logic being run from one of the orphaned PowerShell processes, it's this portion: https://github.com/inspec/train/blob/master/lib/train/transports/local.rb#L188-L217

I've matched the environment as closely as possible, and I have not yet been able to reproduce the issue. Does engineering have any ideas as to what might be causing this, or suggestions on other troubleshooting methods?

**Comment by Vasu1105** [comment]
We have identified the same issue while debugging the multiple Powershell Process are getting created while running Windows Server 2019 remediation cookbook.  The reason behind this is we create the conn using local transport `conn = Train.create('local').connection` it creates the runner pipe here https://github.com/inspec/train/blob/master/lib/train/transports/local.rb#L26, https://github.com/inspec/train/blob/e03fcb161d28cf648dbe6fdbb199556be9d97234/lib/train/transports/local.rb#L51,
https://github.com/inspec/train/blob/e03fcb161d28cf648dbe6fdbb199556be9d97234/lib/train/transports/local.rb#L144,
and this method gets called https://github.com/inspec/train/blob/e03fcb161d28cf648dbe6fdbb199556be9d97234/lib/train/transports/local.rb#L185
in which it this Powershell Process is getting created https://github.com/inspec/train/blob/e03fcb161d28cf648dbe6fdbb199556be9d97234/lib/train/transports/local.rb#L229-L231 but that gets killed only when the Train execution is complete which is nothing but the ruby execution https://github.com/inspec/train/blob/e03fcb161d28cf648dbe6fdbb199556be9d97234/lib/train/transports/local.rb#L234

We also found that there is no implementation of close method where all the processes or sessions which are getting created should get killed. 

We explicitly called the Process.kill with server_pid which resulted into closing that Powershell process.

**Comment by Vasu1105** [comment]
Also like to tag this issue in this as it also talks about the same #475

**Comment by Vasu1105** [comment]
![Screenshot from 2021-01-25 19-07-24](https://user-images.githubusercontent.com/4181545/105713418-27ca1480-5f41-11eb-822f-31429c99b73e.png)
![Screenshot from 2021-01-25 19-08-51](https://user-images.githubusercontent.com/4181545/105713424-2a2c6e80-5f41-11eb-89af-6c31c669f4bb.png)
![Screenshot from 2021-01-25 19-09-05](https://user-images.githubusercontent.com/4181545/105713431-2b5d9b80-5f41-11eb-9792-afdb86cbd8c3.png)
![Screenshot from 2021-01-25 19-09-29](https://user-images.githubusercontent.com/4181545/105713440-2d275f00-5f41-11eb-8801-30eb77ac5cbf.png)
