### ISSUE TITLE
train fails to detect Cisco IOS platform

### ISSUE THREAD

**Issue by jmery** [inspec/train#370]
### Description

Train appears unable to properly detect the platform when attempting to verify the `banner motd` control of the Cisco IOS 15 CIS Level 1 profile.

Previously discussed internally to CHEF with @chris-rock and @anthonygrees 

### Train and Platform Version

train 1.4.35
Cisco IOS 15

### Replication Case

```PowerShell
PS C:\Users\ramalingamr\inspec> inspec exec compliance://admin/cis-ciscoios15-level1_ravi --target ssh://cisco@192.168.10.155 --password 'cisco'
C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:41:inscan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed) from
  C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train1.4.35/lib/train/platforms/detect.rb:9:in scan from 
  C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/plugins/base_connection.rb:102:in platform from
C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train1.4.35/lib/train/extras/command_wrapper.rb:128:in load from 
C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/ssh_connection.rb:53: in initialize
```

### Possible Solutions

N/A

### Stacktrace

N/A

**Comment by jmery** [comment]
@ravitharanr this is the issue for the problem you're seeing

**Comment by jerryaldrichiii** [comment]
Sorry all, just saw this. Could I get a copy of the running config (with sensitive info redacted)?

I suspect this has to do with motd and a bad character.

**Comment by jerryaldrichiii** [comment]
Disregard. I was able to reproduce.

The following banner works:

```
IOS_12_HARDENED(config)#banner motd |       
Enter TEXT message.  End with the character '|'
Banner with a pipe
|
```
However this one does not:

```
IOS_12_HARDENED(config)#banner motd |  
Enter TEXT message.  End with the character '|'
Banner with a pipe |
```

This fails with any character not just a pipe. I suspect this has to do with the not having a new line...which is bizarre.

I'll dig into this if I can this week.

**Comment by ravitharanr** [comment]
Hi Jerry,

Yes, same is for IOS15.

**Comment by jerryaldrichiii** [comment]
@ravitharanr Looks like my fix is merged, if you grab the release of InSpec this Thursday (or Friday) then it should be working now :smile:
