### ISSUE TITLE
OpenSUSE Leap platform detection

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/train#377]
### Description

A user reported an issue in which OpenSUSE Leap is not being detected.  

### Train and Platform Version

InSpec 3.0.12
Train 1.5.??
Target: OpenSUSE Leap 15 (Docker)

### Replication Case

Extensive notes and repro instructions on the original issue, https://github.com/inspec/inspec/issues/3574

### Possible Solutions

Implement or refine SUSE detection

**Comment by megamorf** [comment]
I can see that Train's entire SUSE related detection is based around the existence of `/etc/SuSE-release`: 
https://github.com/inspec/train/blob/03afd4dbb990918bb5443b90b1cb49d3fdaf584f/lib/train/platforms/detect/specifications/os.rb#L225-L242

`/etc/os-release` should be checked as a fallback (see the related issue for its contents) since the official openSUSE Leap Docker image has no `/etc/SuSE-release` file.

**Comment by tas50** [comment]
This also means SLES 15 won’t detect correctly. I’m fixing this on the Ohai side and I can fix it here if no one minds.

**Comment by megamorf** [comment]
@tas50 I've created a corresponding ohai issue yesterday: https://github.com/chef/ohai/issues/1289
My ruby skills are too bad to fix it myself in a reasonable time so your assistance would be appreciated :-)

**Comment by n-rodriguez** [comment]
I think the regex is wrong.

The file `/etc/SuSE-release` exists on openSUSE Leap 15 and its content is :
 
```sh
kitchen@b59935020e63:~> cat /etc/SuSE-release 
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```
Here the regex : 

```ruby

**Comment by tas50** [comment]
I'd suggest in the long run that train moves away from using files like /etc/SuSe-release and instead use /etc/os-release, which exists on every systemd based Linux distro and many distros prior to systemd. It has a standard format and can easily be combined with some case statements to make platform detection much more reliable. I made the switch in Ohai for Chef 15: https://github.com/chef/ohai/pull/1299

**Comment by n-rodriguez** [comment]
@tas50 actually both file has same content : 

```sh
kitchen@b59935020e63:~> cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
kitchen@b59935020e63:~> 
kitchen@b59935020e63:~> 
kitchen@b59935020e63:~> cat /etc/SuSE-release 
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Comment by tas50** [comment]
In this case they are the same, but moving to /etc/os-release as the main detection method allows us to skip a lot of the regex work and just perform some conversions on the ID field instead. That's what we do in ohai so we can remap opensuse-leap to opensuseleap for example. It eliminates dozens of brittle regexes across the different distro specific files. Prior to the os-release detecting platforms was pretty awful.

**Comment by n-rodriguez** [comment]
Thanks for the enlightenment :+1:

**Comment by mcgege** [comment]
> The file `/etc/SuSE-release` exists on openSUSE Leap 15 and its content is :

On a fresh installation this file should not exist - beginning with Leap 15 this file is missing on my systems.

+1 on using /etc/os-release
