### ISSUE TITLE
verify_host_key: false is deprecated, use :never

### ISSUE THREAD

**Issue by alexpop** [inspec/train#384]
`inspec` has started throwing these warnings recently on ssh targets:

```
verify_host_key: false is deprecated, use :never
```

**Comment by chris-rock** [comment]
I've seen this as well.

**Comment by rdonkin** [comment]
Have seen this on InSpec 3.2.6 and also 3.7.1.

**Comment by thbar** [comment]
Same on 3.6.6.

**Comment by maxxware** [comment]
Problem seems to be in verify_host_key: false is deprecated, use :never (line 171). Changed 'false' to ':never' and the message was gone. Tested with chef/inspec Docker image.

**Comment by tas50** [comment]
We need to add this same sort of logic to train if we want to support net-ssh 4 and 5. https://github.com/test-kitchen/test-kitchen/pull/1476/files

**Comment by zenspider** [comment]
I believe this is fixed. Closing.
