### ISSUE TITLE
Publish v1.5.10 to Rubygems

### ISSUE THREAD

**Issue by jaredledvina** [inspec/train#387]
### Description

Amazon Linux 2 detection in Inspec requires train 1.5.10, however, that version is not published to Rubygems. 

See https://github.com/inspec/inspec/pull/3657 which attempts to bump the pinned version of train on the Inspec side. Looks like the latest release was never pushed to Rubygems: https://rubygems.org/gems/train

**Comment by jquick** [comment]
Thanks for this.

1.5.11 has been pushed to rubygems.
