### ISSUE TITLE
Certain commands failing due to STDOUT being parsed by PowerShell

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/train#413]
When executing certain commands on Windows the output is being parsed and throwing and error on PowerShell.

Example:

```
inspec> puts inspec.backend.run_command('java -version').stderr
java.exe : java version "1.8.0_201"
    + CategoryInfo          : NotSpecified: (java version "1.8.0_201":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

Expected output:

```
C:\Users\vagrant>java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

I originally suspected this had to do with the changes I made here: https://github.com/inspec/train/pull/220

Though that change was introduced in Train v0.31.0 (see [CHANGELOG](https://github.com/inspec/train/blob/master/CHANGELOG.md#v0310-2017-12-05)) and the below still shows the error (unless I've done something incorrectly):

```
inspec> VERSION
=> "1.45.13"
inspec> Train::VERSION
=> "0.30.0"
inspec> puts inspec.backend.run_command('java -version').stderr
java.exe : java version "1.8.0_201"
    + CategoryInfo          : NotSpecified: (java version "1.8.0_201":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

Possibly related issues:
  - https://github.com/inspec/inspec/issues/2994
  - https://github.com/inspec/inspec/issues/2993

**Comment by zenspider** [comment]
This is also probably related to the json parsing bugs we've had.

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
