### ISSUE TITLE
Enhance platform metadata

### ISSUE THREAD

**Issue by kevin-j-smith** [inspec/train#417]
### Description

As per, https://github.com/inspec/inspec/issues/3869, there is a need to capture additional information returned in the platform's backend's JSON data.  The most proper place for this is in Train.  The needed information is hostname, domain name and FQDN (all a reported by the machine and not the requestor) as well as network information.   There has also been references to GUID being needed in reporting but is less important, at this time.    

### Train and Platform Version

Inspec is currently using: train (1.7.4)
RHEL variants of Linux/Unix.  

### Replication Case

I ran Train through inspec, but the basic connection and run command should be enough to product the response with platform data.
```basic.rb
require 'train'
Train.create('ssh', hots: '1.2.3.4', port: 22, user: 'youOrMe', key_files: '~/.ssh/sush')
conn = train.connection
puts conn.run_command('whoami').stdout
puts conn.os(:hostname)
puts conn.os(:domainname)
puts conn.os(:fqdn)
puts conn.os(:network)
conn.os(:network).each do |n|
    puts n(:name)
    puts n(:mac)
    puts n(:ips)
    n(:ips).each do |ip|
        puts ip
    end
end
```

### Possible Solutions

By using ruby's socket module and certain linux commands we can gather all of this information from lib/train/platforms/detect/specifications/os.rb.    This is at or near the same time when the family and release information is gathered.  

### Stacktrace

N/A = Feature Request

**Comment by clintoncwolfe** [comment]
Hi @kevin-j-smith , 

  I definitely agree with the need to have this information available to InSpec. However, Train's mission is to connect to remote systems in a consistent manner regardless of transport method. Discovering identifying information falls outside the scope of that mission.

Internally, we've discussed a different approach - having an ohai resource, which could then be queried for this sort of information.  See https://github.com/inspec/inspec/issues/3886, and if you'd be interested in implementing something along those lines, we'd be happy to help.

Thanks again!
