### ISSUE TITLE
sudo password assumes host will have `base64` command

### ISSUE THREAD

**Issue by miah** [inspec/train#445]
The `base64` command is [used](https://github.com/inspec/train/blob/master/lib/train/extras/command_wrapper.rb#L120) to ensure the sudo password is not mangled when passed through train. Some systems, like HPUX and AIX do not have a `base64` command, so this will error:

```
PS> inspec shell --backend=ssh --host=<omitted> --user=USER --password=$env:SudoPassword --sudo --sudo-options=“-u sudouser” --sudo-password=$env:SudoPassword
Sudo failed:  ksh: base64:  not found
Password:
sudo: pam_authenticate: Conversation failure
```

**Comment by RubyTuesdayDONO** [comment]
tbh it was also rather disturbing to see my password in the debug logs, even if superficially hidden by base64 encoding. we owe users better than allowing sensitive confidential data to be leaked in any trivially-discoverable way.
