### ISSUE TITLE
`kitchen verify` results in `sudo` error on `opensuse-leap-15.1` (after `3.2.0`)

### ISSUE THREAD

**Issue by myii** [inspec/train#568]
As requested by @zenspider: https://github.com/inspec/train/issues/548#issuecomment-583132254.

---

# Version:

Any version after `3.2.0`, up to and including `3.2.20`.

# Environment:

Ubuntu Bionic (18.04).

# Scenario:

`kitchen verify` fails with `sudo: no tty present and no askpass program specified]`.

# Steps to Reproduce:

Can be reproduced locally or in Travis.  Here are the steps for the former:

1. Clone https://github.com/saltstack-formulas/openssh-formula
1. Install the gems with respect to the `Gemfile`
1. Run `kitchen verify default-opensuse-leap-151-2019-2-py3` -- this works as expected (`3.2.0`)
1. Install the latest gems for both `train` and `train-core` (i.e. `3.2.20`)
1. Run `kitchen verify default-opensuse-leap-151-2019-2-py3` -- the error shown below is displayed

# Expected Result:

`kitchen verify` completes.

# Actual Result:

```rb
-----> Verifying <default-opensuse-leap-151-2019-2-py3>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Sudo failed: We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified] on default-opensuse-leap-151-2019-2-py3
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by tyler-ball** [comment]
Verified this is no longer an issue in train 3.2.28 - thanks for the easy repro! This will be released in the latest version of Chef Workstation

**Comment by myii** [comment]
> Verified this is no longer an issue in train 3.2.28 - thanks for the easy repro! This will be released in the latest version of Chef Workstation

@tyler-ball You're welcome and thanks for the fix!  I can confirm that it's working now:

* https://travis-ci.org/github/myii/tomcat-formula/jobs/677581937
