### ISSUE TITLE
Support net-ssh < 7.0 and net-scp < 4.0 in gemspec

### ISSUE THREAD

**Issue by fzipi** [inspec/train#584]
# Version:

Any

# Environment:

Any

# Scenario:

Using ssh with better protocols

# Steps to Reproduce:

Using salt to install openssh with strict algorithms and test-kitchen.If using inspec as verifier, now it is not possible to connect to hosts (test-kitchen updated its dependencies in 2.5.0 to net-ssh < 7 and net-scp < 4).

(test-kitchen):
```
  gem.add_dependency "net-scp",            ">= 1.1", "< 4.0" # pinning until we can confirm 4+ works
  gem.add_dependency "net-ssh",            ">= 2.9", "< 7.0" # pinning until we can confirm 7+ works
```

# Expected Result:

Connect to ssh servers with modern configurations.

# Actual Result:

Cannot connect to ssh server, tests fail.

**Comment by fzipi** [comment]
I'm guessing #585 will help in this!

**Comment by tas50** [comment]
@fzipi I realized we didn't have dependabot on this so I set it up, but we need https://github.com/inspec/train/pull/586 merged before dependabot can parse our gemspec/gemfile. After that we should start keeping these deps much more up to date.

**Comment by fzipi** [comment]
@tas50 Excellent, thanks a lot? Do you want me to close this one?

**Comment by tas50** [comment]
We can keep it open until the actual update is made.

**Comment by tas50** [comment]
This was fixed in https://github.com/inspec/train/commit/8ea13b6db8bb957311c7d4dbcf47f1c367ea0fa0#diff-abe2391ce9abe9c21f5cc9d9b15f7a61
