### ISSUE TITLE
Problem with os_windows.rb when the target is cisco_ios

### ISSUE THREAD

**Issue by CodesWhisperer** [inspec/train#599]
https://github.com/inspec/train/blob/c7ff3c059dc89fe68454b3c50b93c15b7a2d65db/lib/train/platforms/detect/helpers/os_windows.rb#L36-L38

When the target is a cisco_ios device, the exit_status is 0 but the error is described in the stdout, so the if condition doesn't work and the JSON.parse raises an exception.

To fix it, the if should be something like:
`return false if (command.exit_status != 0) || command.stdout.empty? || !(command.stdout.downcase =~ /window/)`

This line alone fixed it for me, but I also think the JSON.parse should be inside rescue block.

**Comment by Schwad** [comment]
Hey @CodesWhisperer  👋 

Thanks for the issue! Would you like to open a PR with this change so we can continue the discussion there?

**Comment by tas50** [comment]
Closing this out since we shipped the fix. Thanks @CodesWhisperer
