### ISSUE TITLE
Product string changing from 'MacOS X' to 'macOS' in 10.16

### ISSUE THREAD

**Issue by james-stocks** [inspec/train#617]
Ref: https://github.com/inspec/inspec/pull/5130

macOS 11 Big Sur will be released later this year. Current beta versions return 10.16 as the version, but the product name has changed from 'MacOS X' to 'macOS'. 

We need to support that new product string.

**Comment by tas50** [comment]
We should make sure to map the new product name to the existing platform name so we have consistent behavior with ohai.

**Comment by tas50** [comment]
Fixed in #618
