### ISSUE TITLE
Add support for AlmaLinux

### ISSUE THREAD

**Issue by btm** [inspec/train#662]
[AlmaLinux](https://almalinux.org/) is a CentOS successor sponsored by CloudLinux.

> AlmaLinux is a 1:1 binary compatible fork of RHEL® 8 and it is built by the creators of the established CloudLinux OS.

We need to detect it for the redhat family. This change was already made in ohai (https://github.com/chef/ohai/pull/1604).

**Comment by clintoncwolfe** [comment]
Using train 3.4.10 and the AlmaLinux vagrant box v8.3.20210203, running `inspec detect` currently gives this result:

```
 ────────────────────────────── Platform Details ──────────────────────────────

Name:      almalinux
Families:  redhat, linux, unix, os
Release:   8.3
Arch:      x86_64
```

That appears to be the correct response, unless I am missing something.

**Comment by btm** [comment]
@clintoncwolfe that looks correct. Thanks for testing. I looked at the code and it wasn't clear to me how that practically work. I asked @tas50 and he thinks this is correct too.

**Comment by tas50** [comment]
I think we're good here. Thanks @clintoncwolfe
