### ISSUE TITLE
Detect UbiOS

### ISSUE THREAD

**Issue by tas50** [inspec/train#684]
# Version:

3.7.0

# Environment:

macOS host running Ruby 2.7.3

target mode: unifi udm pro via SSH

# Scenario:

The UbiOS on Unifi UDM hardware is not detected properly even though it's a pretty stock Linux distro and Ohai detects it just fine.

Content of /etc/os-release

```
# cat /etc/os-release
NAME=UbiOS
VERSION=UDM.alpinev2.v1.9.3.50c9676.210401.1021
ID=ubios
VERSION_ID=v1.9.3.3438-50c9676
PRETTY_NAME="UbiOS 1.9.3.3438"
BUILD_ID=210401.1021
VARIANT=UDM.alpinev2
```

**Comment by clintoncwolfe** [comment]
Added in #687
